"""
IrisPathQ: MILP vs MILP+QAOA
Uses WEATHER-AWARE MILP cost matrix generated by milp_weather.o
"""

import numpy as np
from qiskit import QuantumCircuit, transpile
from qiskit_aer import Aer
from scipy.optimize import minimize
import sys

print("=" * 90)
print("IRIS PATHQ - MILP (WEATHER) vs MILP+QAOA COMPARISON")
print("=" * 90)

# ---------------------------------------------------------------------
# 1. LOAD WEATHER-AWARE MILP COST MATRIX
# ---------------------------------------------------------------------
print("\n[1] Loading MILP (weather) cost matrix with conflict injection...")

MATRIX_FILE = "output/cost_matrix_milp_weather.txt"

try:
    with open(MATRIX_FILE, "r") as f:
        lines = f.readlines()

    matrix_size = int(lines[0].strip())
    cost_matrix = np.zeros((matrix_size, matrix_size))

    for line in lines[1:]:
        parts = line.strip().split(',')
        if len(parts) == 3:
            i, j, v = int(parts[0]), int(parts[1]), float(parts[2])
            cost_matrix[i][j] = v

    print(f"  Loaded {matrix_size}×{matrix_size} matrix (weather-aware)")

except FileNotFoundError:
    print(f"   ERROR: Could not find {MATRIX_FILE}")
    print("   Run ./milp_weather first!")
    sys.exit(1)

# ---------------------------------------------------------------------
# Problem Definition
# ---------------------------------------------------------------------
NUM_FLIGHTS = 5
ROUTES_PER_FLIGHT = matrix_size // NUM_FLIGHTS

print(f"   Problem = {NUM_FLIGHTS} flights × {ROUTES_PER_FLIGHT} routes")

# ---------------------------------------------------------------------
# 2. MILP GREEDY BASELINE
# ---------------------------------------------------------------------
print("\n[2] Computing MILP greedy (fuel-only) solution...")

milp_solution = []
milp_fuel = 0.0

for f in range(NUM_FLIGHTS):
    start = f * ROUTES_PER_FLIGHT
    end = start + ROUTES_PER_FLIGHT

    best = min(range(start, end), key=lambda r: cost_matrix[r][r])
    milp_solution.append(best)
    milp_fuel += cost_matrix[best][best]

# Count pairwise conflicts
milp_conflicts = 0
milp_conflict_cost = 0.0

for i in range(NUM_FLIGHTS):
    for j in range(i + 1, NUM_FLIGHTS):
        penalty = cost_matrix[milp_solution[i]][milp_solution[j]]
        if penalty > 0:
            milp_conflicts += 1
            milp_conflict_cost += penalty

milp_total = milp_fuel + milp_conflict_cost

# convert global route indices → local route numbers
milp_routes = [r % ROUTES_PER_FLIGHT for r in milp_solution]

print(f"\n   MILP (Weather) Greedy Routes: {milp_routes}")
print(f"   Fuel:      {milp_fuel:,.0f} kg")
print(f"   Conflicts: {milp_conflicts}  (penalty {milp_conflict_cost:,.0f})")
print(f"   TOTAL:     {milp_total:,.0f} kg")

# ---------------------------------------------------------------------
# 3. QAOA SETUP
# ---------------------------------------------------------------------
print("\n[3] Optimizing with QAOA...\n")

QUBITS_PER_FLIGHT = 3   # 3 bits → 8 possible routes (fits 5)
num_qubits = NUM_FLIGHTS * QUBITS_PER_FLIGHT

simulator = Aer.get_backend("qasm_simulator")

def bitstring_to_solution(bitstring):
    clean = bitstring.replace(" ", "")
    bits = [int(b) for b in clean]

    sol = []
    for f in range(NUM_FLIGHTS):
        base = f * QUBITS_PER_FLIGHT
        a, b, c = bits[base:base+3]
        route_num = (a << 2) + (b << 1) + c

        if route_num < ROUTES_PER_FLIGHT:
            sol.append(f * ROUTES_PER_FLIGHT + route_num)
        else:
            sol.append(f * ROUTES_PER_FLIGHT)

    return sol

def compute_cost(bitstring):
    sol = bitstring_to_solution(bitstring)
    fuel = sum(cost_matrix[r][r] for r in sol)
    conflicts = 0

    for i in range(NUM_FLIGHTS):
        for j in range(i + 1, NUM_FLIGHTS):
            conflicts += cost_matrix[sol[i]][sol[j]]

    # penalty for invalid 3-bit encoding
    penalty = 0
    clean = bitstring.replace(" ", "")
    bits = [int(b) for b in clean]

    for f in range(NUM_FLIGHTS):
        a, b, c = bits[f*3:f*3+3]
        route_num = (a << 2) + (b << 1) + c
        if route_num >= ROUTES_PER_FLIGHT:
            penalty += 50000

    return fuel + conflicts + penalty, sol

def create_qaoa(gamma, beta):
    qc = QuantumCircuit(num_qubits, num_qubits)
    qc.h(range(num_qubits))

    # COST (fuel) LAYER
    for f in range(NUM_FLIGHTS):
        base = f * QUBITS_PER_FLIGHT
        offset = f * ROUTES_PER_FLIGHT

        for r in range(ROUTES_PER_FLIGHT):
            fuel = cost_matrix[offset + r][offset + r]
            angle = gamma * (fuel / 8000.0)  # normalize

            if r & 1: qc.rz(angle, base + 2)
            if r & 2: qc.rz(angle, base + 1)
            if r & 4: qc.rz(angle, base + 0)

    # MIXER
    for q in range(num_qubits):
        qc.rx(beta, q)
        qc.ry(beta * 0.4, q)

    qc.measure_all()
    return qc

def run_circuit(gamma, beta):
    qc = create_qaoa(gamma, beta)
    compiled = transpile(qc, simulator)
    result = simulator.run(compiled, shots=1024).result()
    counts = result.get_counts()

    total = 0
    shots = sum(counts.values())

    for s, cnt in counts.items():
        c, _ = compute_cost(s)
        total += c * cnt

    return total / shots

# ---------------------------------------------------------------------
# 4. OPTIMIZATION
# ---------------------------------------------------------------------
print("Optimizing QAOA parameters using COBYLA...")

def objective(params):
    gamma, beta = params
    return run_circuit(gamma, beta)

res = minimize(objective,
               x0=[0.4, 0.5],
               method="COBYLA",
               options={'maxiter': 8})

gamma_opt, beta_opt = res.x
print(f"Optimal γ={gamma_opt:.3f}, β={beta_opt:.3f}\n")

# ---------------------------------------------------------------------
# 5. FINAL QAOA RUN
# ---------------------------------------------------------------------
print("Final QAOA execution (weather-aware MILP cost)...")

qc_final = create_qaoa(gamma_opt, beta_opt)
compiled = transpile(qc_final, simulator)
result = simulator.run(compiled, shots=4096).result()
counts = result.get_counts()

best_cost = float("inf")
best_solution = None

for s, cnt in counts.items():
    c, sol = compute_cost(s)
    if c < best_cost:
        best_cost = c
        best_solution = sol

qaoa_routes = [r % ROUTES_PER_FLIGHT for r in best_solution]
qaoa_fuel = sum(cost_matrix[r][r] for r in best_solution)
qaoa_conflicts = sum(
    cost_matrix[best_solution[i]][best_solution[j]]
    for i in range(NUM_FLIGHTS)
    for j in range(i+1, NUM_FLIGHTS)
)

qaoa_total = qaoa_fuel + qaoa_conflicts

print(f"\nQAOA Best Routes: {qaoa_routes}")
print(f"Fuel: {qaoa_fuel:,.0f} kg")
print(f"Conflicts Penalty: {qaoa_conflicts:,.0f} kg")
print(f"TOTAL: {qaoa_total:,.0f} kg")

# ---------------------------------------------------------------------
# 6. COMPARISON
# ---------------------------------------------------------------------
print("\n" + "="*90)
print("MILP (Weather) vs MILP+QAOA")
print("="*90)

improvement = milp_total - qaoa_total

print(f"\nMILP Weather Total:  {milp_total:,.0f} kg")
print(f"QAOA Weather Total:  {qaoa_total:,.0f} kg")
print(f"Improvement:         {improvement:,.0f} kg")
